[package]
name = "uni_stego"
version = "0.2.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
clap-stdin = "0.6"
anyhow = "1.0"
bitvec = "1"
phf = { version = "0.11", features = ["macros"] }
